let products = [
    {
        id : 1,
        category : "Product : Bag",
        title : "Bag Black",
        price :  300,
        imageUrl : "images/bag1.jpg",
        quantity : 1 ,
     },
    {
        id : 2,
        category : "Product : Pen",
        title : "Pen",
        price :  20,
        imageUrl : "images/pens.jpg",
        quantity : 1 ,
    },
    {
        id : 3,
        category : "Product : Bag",
        title : "Bag Violet",
        price :  500,
        imageUrl : "images/bag3.jpg",
        quantity : 1 ,
    },
    {
        id : 4,
        category : "Product : Table",
        title : "Table Wooden",
        price :  250,
        imageUrl : "images/table.jpg",
        quantity : 1 ,
    },
    {
        id : 5,
        category : "Product : Pencil",
        title : "Pencil Yellow",
        price :  10,
        imageUrl : "images/pencil.png",
        quantity : 1 ,
    },
    {
        id : 6,
        category : "Product : Pen",
        title : "Colors-pens",
        price :  60,
        imageUrl : "images/colors-pens.jpg",
        quantity : 1 ,
    },
]